server:
  port: 4000
spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/CORE_DB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update #create-drop
    show-sql: true
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
logging:
  level:
    root: info